### ISSUE TITLE
[2022/10/03] Ioannis Semertzis - anomaly detection in RESCUE

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/Machine_Learning_SIG#45]
- description/abstract: Ioannis will introduce his [RESCUE project](https://www.esciencecenter.nl/projects/resilience-and-cyber-security-of-integrated-cyber-physical-energy-systems-rescue/) and describe his problem that he tries to solve using anomaly detection.
- approximate duration: 50 mins
- difficulty:
- other notes:

**Comment by isemertzis** [comment]
- **Presenter**: Ioannis Semertzis, PhD candidate TU Delft

- **Description/ Abstract**: During the past decade, critical infrastructures such as power systems are targeted by cyber actors. As shown in the cyber attacks in 2015 and 2016 in Ukraine, power system operation can be affected by malicious actors, causing outages. As these systems are not designed with cyber security considerations, such attacks could result in cascading failures in the physical system and even blackouts. The RESCUE project aims to develop methods and technologies for incident response to cyber attacks and to secure the Control Room of the Future. This presentation will be divided into three parts. Firstly, an overview of the RESCUE project will be given. Then, the proposed intrusion detection system based on convolutional neural networks (CNN) and Long-short Term Memory (LSTM) will be presented. Finally, the application of digital twins, necessary for generating the real-time cyber-physical data used for anomaly detection will be also discussed. 

- **Approximate Duration**: 50 mins

- other notes:
