### ISSUE TITLE
[2022/09/19] Victor Pereboom - DeepDive UbiOps

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/Machine_Learning_SIG#48]
- description/abstract: [UbiOps](https://t.sidekickopen01.com/s3t/c/5/f18dQhb0S7kF8bGk8VVz_0qp59hl3kW7_k2841CXdp3VPwNb557QR_rW2dykcb8KrJDS101?te=W3R5hFj26QkHkW3C9qZz4cg7sG348S2&si=8000000003143717&pi=477b54b6-6ac0-456b-b800-6a0427d49131) is a middleware/MLOps layer that is used by ML and AI researchers and practitioners to run, manage and scale AI and ML workloads without the need to setup and manage complex infrastructure. UbiOps multi- and hybrid cloud capability provides a way to lift and shift workloads between different clusters, optimising resource availability. During the session Victor Pereboom will introduce UbiOps and provide a demonstration of the platform - both for training and inferencing jobs. UbiOps is used by research organisations such as SURF, and universities like the Eindhoven University of Technology. Technical documentation can be found [here](https://t.sidekickopen01.com/s3t/c/5/f18dQhb0S7kF8bGk8VVz_0qp59hl3kW7_k2841CXdp3VPwNb557QR_rW2dykcb8KrJDS101?te=W3R5hFj4cm2zwW4hCVHc45V723W43T4NT43P1-Z0&si=8000000003143717&pi=477b54b6-6ac0-456b-b800-6a0427d49131).

- approximate duration:
- difficulty:
- other notes:

**Comment by elboyran** [comment]
- Victor Pereboom - CTO UbiOps (main presenter) 
- Kees van Bezouw - Product Specialist UbiOps

Short description
[UbiOps](https://t.sidekickopen01.com/s3t/c/5/f18dQhb0S7kF8bGk8VVz_0qp59hl3kW7_k2841CXdp3VPwNb557QR_rW2dykcb8KrJDS101?te=W3R5hFj26QkHkW3C9qZz4cg7sG348S2&si=8000000003143717&pi=477b54b6-6ac0-456b-b800-6a0427d49131) is a middleware/MLOps layer that is used by ML and AI researchers and practitioners to run, manage and scale AI and ML workloads without the need to setup and manage complex infrastructure. UbiOps multi- and hybrid cloud capability provides a way to lift and shift workloads between different clusters, optimising resource availability. During the session Victor Pereboom will introduce UbiOps and provide a demonstration of the platform - both for training and inferencing jobs. UbiOps is used by research organisations such as SURF, and universities like the Eindhoven University of Technology. Technical documentation can be found [here](https://t.sidekickopen01.com/s3t/c/5/f18dQhb0S7kF8bGk8VVz_0qp59hl3kW7_k2841CXdp3VPwNb557QR_rW2dykcb8KrJDS101?te=W3R5hFj4cm2zwW4hCVHc45V723W43T4NT43P1-Z0&si=8000000003143717&pi=477b54b6-6ac0-456b-b800-6a0427d49131).
