### ISSUE TITLE
[2023/05/11] Ying Ying Ma - Equivariant Diffusion Models for molecule generation

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/Machine_Learning_SIG#60]
- description/abstract: Ying Ying Ma, L.A. of DeppMolGen ML SSI project, will present an overview (Literature and first experiments) of Equivariant Diffusion Models for molecule generation.
- approximate duration:
- difficulty:
- other notes:

**Comment by luisaforozco** [comment]
Hi Chris, could we host a presentation of some collaborators form UvA ?
I'm specifically thinking about Ying Ying Ma, a MSc student of Bernd Ensig (L.A. of DeppMolGen a current project of ML SSI).
She would present an overview (Literature and first experiments) of Equivariant Diffusion Models for molecule generation.
I have already talking with them and this spot would be perfect for them.
